controller_frequency: 2
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
   max_vel_x: 0.2
   min_vel_x: 0.01
   max_vel_theta: 0.01
   min_vel_theta: -0.01
   acc_lim_x: 1
   acc_lim_y: 1  
   acc_lim_theta: 0.5
   y_vels: [-0.2, -0.01, 0.01, 0.2]

   holonomic_robot: ture
   yaw_goal_tolerance: 0.2 
   xy_goal_tolerance: 0.2
   latch_xy_goal_tolerance: false
   pdist_scale: 0.9
   gdist_scale: 0.4
   meter_scoring: true

   occdist_scale: 0.1
   sim_time: 1.0
   dwa: true


   


