local_costmap:
   global_frame: odom
   robot_base_frame: base_link
   update_frequency: 5.0
   publish_frequency: 1.0
   static_map: false
   rolling_window: true
   width: 1.2
   height: 1.2
   resolution: 0.01
   transform_tolerance: 1.0
